/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type AdminVerificationActionAction = (typeof AdminVerificationActionAction)[keyof typeof AdminVerificationActionAction];
export declare const AdminVerificationActionAction: {
    readonly approve: "approve";
    readonly reject: "reject";
};
//# sourceMappingURL=adminVerificationActionAction.d.ts.map