/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Deducts one boost from the seller's available boosts and features the listing for 7 days
 * @summary Apply a boost to a gemstone listing
 */
export declare const BoostListingParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const BoostListingBody: zod.ZodObject<{
    seller_id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    seller_id: string;
}, {
    seller_id: string;
}>;
export declare const BoostListingResponse: zod.ZodObject<{
    gemstone_id: zod.ZodString;
    is_featured: zod.ZodBoolean;
    boost_expiry_date: zod.ZodDate;
    boosts_remaining: zod.ZodNumber;
    boost_cost_usd: zod.ZodNumber;
    expires_in_days: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    gemstone_id: string;
    is_featured: boolean;
    boost_expiry_date: Date;
    boosts_remaining: number;
    boost_cost_usd: number;
    expires_in_days: number;
}, {
    gemstone_id: string;
    is_featured: boolean;
    boost_expiry_date: Date;
    boosts_remaining: number;
    boost_cost_usd: number;
    expires_in_days: number;
}>;
/**
 * Adds boosts to the seller's available boost balance
 * @summary Purchase a boost pack
 */
export declare const BuyBoostPackParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const BuyBoostPackBody: zod.ZodObject<{
    pack: zod.ZodEnum<["boosts_5", "boosts_10"]>;
}, "strip", zod.ZodTypeAny, {
    pack: "boosts_5" | "boosts_10";
}, {
    pack: "boosts_5" | "boosts_10";
}>;
export declare const BuyBoostPackResponse: zod.ZodObject<{
    pack: zod.ZodEnum<["boosts_5", "boosts_10"]>;
    boosts_added: zod.ZodNumber;
    cost_usd: zod.ZodNumber;
    boosts_available: zod.ZodNumber;
    standard_price_per_boost: zod.ZodNumber;
    effective_price_per_boost: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    pack: "boosts_5" | "boosts_10";
    boosts_added: number;
    cost_usd: number;
    boosts_available: number;
    standard_price_per_boost: number;
    effective_price_per_boost: number;
}, {
    pack: "boosts_5" | "boosts_10";
    boosts_added: number;
    cost_usd: number;
    boosts_available: number;
    standard_price_per_boost: number;
    effective_price_per_boost: number;
}>;
/**
 * @summary Get current launch period status and pricing
 */
export declare const GetLaunchConfigResponse: zod.ZodObject<{
    is_launch_period: zod.ZodBoolean;
    verification_fees: zod.ZodObject<{
        basic_verified: zod.ZodNumber;
        premium_verified: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        basic_verified: number;
        premium_verified: number;
    }, {
        basic_verified: number;
        premium_verified: number;
    }>;
    subscription_pricing: zod.ZodObject<{
        starter: zod.ZodNumber;
        growth: zod.ZodNumber;
        pro: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        starter: number;
        growth: number;
        pro: number;
    }, {
        starter: number;
        growth: number;
        pro: number;
    }>;
    free_boosts_granted: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    is_launch_period: boolean;
    verification_fees: {
        basic_verified: number;
        premium_verified: number;
    };
    subscription_pricing: {
        starter: number;
        growth: number;
        pro: number;
    };
    free_boosts_granted: number;
}, {
    is_launch_period: boolean;
    verification_fees: {
        basic_verified: number;
        premium_verified: number;
    };
    subscription_pricing: {
        starter: number;
        growth: number;
        pro: number;
    };
    free_boosts_granted: number;
}>;
/**
 * @summary Enable or disable the launch period
 */
export declare const SetLaunchPeriodBody: zod.ZodObject<{
    is_launch_period: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    is_launch_period: boolean;
}, {
    is_launch_period: boolean;
}>;
export declare const SetLaunchPeriodResponse: zod.ZodObject<{
    is_launch_period: zod.ZodBoolean;
    verification_fees: zod.ZodObject<{
        basic_verified: zod.ZodNumber;
        premium_verified: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        basic_verified: number;
        premium_verified: number;
    }, {
        basic_verified: number;
        premium_verified: number;
    }>;
    subscription_pricing: zod.ZodObject<{
        starter: zod.ZodNumber;
        growth: zod.ZodNumber;
        pro: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        starter: number;
        growth: number;
        pro: number;
    }, {
        starter: number;
        growth: number;
        pro: number;
    }>;
    free_boosts_granted: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    is_launch_period: boolean;
    verification_fees: {
        basic_verified: number;
        premium_verified: number;
    };
    subscription_pricing: {
        starter: number;
        growth: number;
        pro: number;
    };
    free_boosts_granted: number;
}, {
    is_launch_period: boolean;
    verification_fees: {
        basic_verified: number;
        premium_verified: number;
    };
    subscription_pricing: {
        starter: number;
        growth: number;
        pro: number;
    };
    free_boosts_granted: number;
}>;
/**
 * Buyer creates a new transaction for a gemstone
 * @summary Create a transaction request
 */
export declare const createTransactionBodyTotalAmountMin = 0;
export declare const createTransactionBodyAdvancePaidMin = 0;
export declare const createTransactionBodyCreditAmountMin = 0;
export declare const CreateTransactionBody: zod.ZodObject<{
    buyer_id: zod.ZodString;
    seller_id: zod.ZodString;
    inventory_id: zod.ZodString;
    total_amount: zod.ZodNumber;
    currency: zod.ZodEnum<["USD", "INR", "AED"]>;
    advance_paid: zod.ZodNumber;
    credit_amount: zod.ZodNumber;
    due_date: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    seller_id: string;
    buyer_id: string;
    inventory_id: string;
    total_amount: number;
    currency: "USD" | "INR" | "AED";
    advance_paid: number;
    credit_amount: number;
    due_date: Date;
}, {
    seller_id: string;
    buyer_id: string;
    inventory_id: string;
    total_amount: number;
    currency: "USD" | "INR" | "AED";
    advance_paid: number;
    credit_amount: number;
    due_date: Date;
}>;
/**
 * Record a payment against a transaction
 * @summary Record a payment
 */
export declare const createPaymentBodyAmountMin = 0;
export declare const CreatePaymentBody: zod.ZodObject<{
    transaction_id: zod.ZodString;
    amount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    transaction_id: string;
    amount: number;
}, {
    transaction_id: string;
    amount: number;
}>;
/**
 * Returns credit score, total outstanding and overdue amounts for a buyer. Only accessible to PRO plan sellers.
 * @summary Get buyer credit summary (PRO sellers only)
 */
export declare const GetBuyerCreditSummaryParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const GetBuyerCreditSummaryQueryParams: zod.ZodObject<{
    requester_id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    requester_id: string;
}, {
    requester_id: string;
}>;
export declare const getBuyerCreditSummaryResponseCreditScoreMin = 300;
export declare const getBuyerCreditSummaryResponseCreditScoreMax = 850;
export declare const getBuyerCreditSummaryResponseTransactionsItemTotalAmountMin = 0;
export declare const getBuyerCreditSummaryResponseTransactionsItemAdvancePaidMin = 0;
export declare const getBuyerCreditSummaryResponseTransactionsItemCreditAmountMin = 0;
export declare const GetBuyerCreditSummaryResponse: zod.ZodObject<{
    buyer_id: zod.ZodString;
    credit_score: zod.ZodNumber;
    credit_rating: zod.ZodString;
    total_outstanding: zod.ZodNumber;
    overdue_amount: zod.ZodNumber;
    completed_transactions: zod.ZodNumber;
    overdue_transactions: zod.ZodNumber;
    transactions: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        buyer_id: zod.ZodString;
        seller_id: zod.ZodString;
        inventory_id: zod.ZodString;
        total_amount: zod.ZodNumber;
        currency: zod.ZodEnum<["USD", "INR", "AED"]>;
        advance_paid: zod.ZodNumber;
        credit_amount: zod.ZodNumber;
        due_date: zod.ZodDate;
        status: zod.ZodEnum<["pending", "completed", "overdue"]>;
        created_at: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        status: "pending" | "completed" | "overdue";
        id: string;
        seller_id: string;
        buyer_id: string;
        inventory_id: string;
        total_amount: number;
        currency: "USD" | "INR" | "AED";
        advance_paid: number;
        credit_amount: number;
        due_date: Date;
        created_at: Date;
    }, {
        status: "pending" | "completed" | "overdue";
        id: string;
        seller_id: string;
        buyer_id: string;
        inventory_id: string;
        total_amount: number;
        currency: "USD" | "INR" | "AED";
        advance_paid: number;
        credit_amount: number;
        due_date: Date;
        created_at: Date;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    buyer_id: string;
    credit_score: number;
    credit_rating: string;
    total_outstanding: number;
    overdue_amount: number;
    completed_transactions: number;
    overdue_transactions: number;
    transactions: {
        status: "pending" | "completed" | "overdue";
        id: string;
        seller_id: string;
        buyer_id: string;
        inventory_id: string;
        total_amount: number;
        currency: "USD" | "INR" | "AED";
        advance_paid: number;
        credit_amount: number;
        due_date: Date;
        created_at: Date;
    }[];
}, {
    buyer_id: string;
    credit_score: number;
    credit_rating: string;
    total_outstanding: number;
    overdue_amount: number;
    completed_transactions: number;
    overdue_transactions: number;
    transactions: {
        status: "pending" | "completed" | "overdue";
        id: string;
        seller_id: string;
        buyer_id: string;
        inventory_id: string;
        total_amount: number;
        currency: "USD" | "INR" | "AED";
        advance_paid: number;
        credit_amount: number;
        due_date: Date;
        created_at: Date;
    }[];
}>;
/**
 * @summary Update seller subscription plan
 */
export declare const UpdateSubscriptionPlanParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const UpdateSubscriptionPlanBody: zod.ZodObject<{
    plan: zod.ZodEnum<["starter", "growth", "pro"]>;
}, "strip", zod.ZodTypeAny, {
    plan: "starter" | "growth" | "pro";
}, {
    plan: "starter" | "growth" | "pro";
}>;
export declare const updateSubscriptionPlanResponseFreeBoostsMin = 0;
export declare const UpdateSubscriptionPlanResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
    verification_status: zod.ZodEnum<["unverified", "basic_verified", "premium_verified"]>;
    verification_fee_paid: zod.ZodBoolean;
    verification_badge: zod.ZodEnum<["none", "basic_verified", "premium_verified"]>;
    requested_tier: zod.ZodOptional<zod.ZodEnum<["basic_verified", "premium_verified"]>>;
    subscription_plan: zod.ZodEnum<["starter", "growth", "pro"]>;
    free_boosts: zod.ZodNumber;
    is_founding_seller: zod.ZodBoolean;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}>;
/**
 * User pays the verification fee and requests a tier upgrade
 * @summary Submit verification fee payment
 */
export declare const SubmitVerificationRequestParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const SubmitVerificationRequestBody: zod.ZodObject<{
    tier: zod.ZodEnum<["basic_verified", "premium_verified"]>;
}, "strip", zod.ZodTypeAny, {
    tier: "basic_verified" | "premium_verified";
}, {
    tier: "basic_verified" | "premium_verified";
}>;
export declare const submitVerificationRequestResponseFreeBoostsMin = 0;
export declare const SubmitVerificationRequestResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
    verification_status: zod.ZodEnum<["unverified", "basic_verified", "premium_verified"]>;
    verification_fee_paid: zod.ZodBoolean;
    verification_badge: zod.ZodEnum<["none", "basic_verified", "premium_verified"]>;
    requested_tier: zod.ZodOptional<zod.ZodEnum<["basic_verified", "premium_verified"]>>;
    subscription_plan: zod.ZodEnum<["starter", "growth", "pro"]>;
    free_boosts: zod.ZodNumber;
    is_founding_seller: zod.ZodBoolean;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}>;
/**
 * @summary Admin approves or rejects a verification request
 */
export declare const AdminVerifyUserParams: zod.ZodObject<{
    id: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const AdminVerifyUserBody: zod.ZodObject<{
    action: zod.ZodEnum<["approve", "reject"]>;
}, "strip", zod.ZodTypeAny, {
    action: "approve" | "reject";
}, {
    action: "approve" | "reject";
}>;
export declare const adminVerifyUserResponseFreeBoostsMin = 0;
export declare const AdminVerifyUserResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
    verification_status: zod.ZodEnum<["unverified", "basic_verified", "premium_verified"]>;
    verification_fee_paid: zod.ZodBoolean;
    verification_badge: zod.ZodEnum<["none", "basic_verified", "premium_verified"]>;
    requested_tier: zod.ZodOptional<zod.ZodEnum<["basic_verified", "premium_verified"]>>;
    subscription_plan: zod.ZodEnum<["starter", "growth", "pro"]>;
    free_boosts: zod.ZodNumber;
    is_founding_seller: zod.ZodBoolean;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}>;
/**
 * Returns all gemstones listed on GemWorld
 * @summary List all gemstones
 */
export declare const listInventoryResponseCaratMin = 0;
export declare const listInventoryResponsePriceMin = 0;
export declare const listInventoryResponseBasePriceUsdMin = 0;
export declare const listInventoryResponseEstimatedPriceMinMin = 0;
export declare const listInventoryResponseEstimatedPriceMaxMin = 0;
export declare const ListInventoryResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    seller_id: zod.ZodString;
    stone_type: zod.ZodString;
    carat: zod.ZodNumber;
    origin: zod.ZodString;
    treatment: zod.ZodString;
    price: zod.ZodNumber;
    currency: zod.ZodEnum<["USD", "INR", "AED"]>;
    base_price_usd: zod.ZodNumber;
    certificate_number: zod.ZodString;
    image_url: zod.ZodString;
    color: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    clarity: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    rap_price_per_carat: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    total_rap_value: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    is_featured: zod.ZodBoolean;
    boost_expiry_date: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    estimated_price_min: zod.ZodNumber;
    estimated_price_max: zod.ZodNumber;
    pricing_confidence: zod.ZodEnum<["low", "medium", "high"]>;
    pricing_disclaimer: zod.ZodString;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    seller_id: string;
    is_featured: boolean;
    currency: "USD" | "INR" | "AED";
    created_at: Date;
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    base_price_usd: number;
    certificate_number: string;
    image_url: string;
    estimated_price_min: number;
    estimated_price_max: number;
    pricing_confidence: "low" | "medium" | "high";
    pricing_disclaimer: string;
    boost_expiry_date?: Date | null | undefined;
    color?: string | null | undefined;
    clarity?: string | null | undefined;
    rap_price_per_carat?: number | null | undefined;
    total_rap_value?: number | null | undefined;
}, {
    id: string;
    seller_id: string;
    is_featured: boolean;
    currency: "USD" | "INR" | "AED";
    created_at: Date;
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    base_price_usd: number;
    certificate_number: string;
    image_url: string;
    estimated_price_min: number;
    estimated_price_max: number;
    pricing_confidence: "low" | "medium" | "high";
    pricing_disclaimer: string;
    boost_expiry_date?: Date | null | undefined;
    color?: string | null | undefined;
    clarity?: string | null | undefined;
    rap_price_per_carat?: number | null | undefined;
    total_rap_value?: number | null | undefined;
}>;
export declare const ListInventoryResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    seller_id: zod.ZodString;
    stone_type: zod.ZodString;
    carat: zod.ZodNumber;
    origin: zod.ZodString;
    treatment: zod.ZodString;
    price: zod.ZodNumber;
    currency: zod.ZodEnum<["USD", "INR", "AED"]>;
    base_price_usd: zod.ZodNumber;
    certificate_number: zod.ZodString;
    image_url: zod.ZodString;
    color: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    clarity: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    rap_price_per_carat: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    total_rap_value: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    is_featured: zod.ZodBoolean;
    boost_expiry_date: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    estimated_price_min: zod.ZodNumber;
    estimated_price_max: zod.ZodNumber;
    pricing_confidence: zod.ZodEnum<["low", "medium", "high"]>;
    pricing_disclaimer: zod.ZodString;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    seller_id: string;
    is_featured: boolean;
    currency: "USD" | "INR" | "AED";
    created_at: Date;
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    base_price_usd: number;
    certificate_number: string;
    image_url: string;
    estimated_price_min: number;
    estimated_price_max: number;
    pricing_confidence: "low" | "medium" | "high";
    pricing_disclaimer: string;
    boost_expiry_date?: Date | null | undefined;
    color?: string | null | undefined;
    clarity?: string | null | undefined;
    rap_price_per_carat?: number | null | undefined;
    total_rap_value?: number | null | undefined;
}, {
    id: string;
    seller_id: string;
    is_featured: boolean;
    currency: "USD" | "INR" | "AED";
    created_at: Date;
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    base_price_usd: number;
    certificate_number: string;
    image_url: string;
    estimated_price_min: number;
    estimated_price_max: number;
    pricing_confidence: "low" | "medium" | "high";
    pricing_disclaimer: string;
    boost_expiry_date?: Date | null | undefined;
    color?: string | null | undefined;
    clarity?: string | null | undefined;
    rap_price_per_carat?: number | null | undefined;
    total_rap_value?: number | null | undefined;
}>, "many">;
/**
 * Seller adds a new gemstone to inventory
 * @summary Add a gemstone listing
 */
export declare const addGemstoneBodyCaratMin = 0;
export declare const addGemstoneBodyPriceMin = 0;
export declare const AddGemstoneBody: zod.ZodObject<{
    seller_id: zod.ZodString;
    stone_type: zod.ZodString;
    carat: zod.ZodNumber;
    origin: zod.ZodString;
    treatment: zod.ZodString;
    color: zod.ZodOptional<zod.ZodString>;
    clarity: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodNumber;
    currency: zod.ZodEnum<["USD", "INR", "AED"]>;
    certificate_number: zod.ZodString;
    image_url: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    seller_id: string;
    currency: "USD" | "INR" | "AED";
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    certificate_number: string;
    image_url: string;
    color?: string | undefined;
    clarity?: string | undefined;
}, {
    seller_id: string;
    currency: "USD" | "INR" | "AED";
    stone_type: string;
    carat: number;
    origin: string;
    treatment: string;
    price: number;
    certificate_number: string;
    image_url: string;
    color?: string | undefined;
    clarity?: string | undefined;
}>;
/**
 * Returns a list of all registered users
 * @summary List all users
 */
export declare const listUsersResponseFreeBoostsMin = 0;
export declare const ListUsersResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
    verification_status: zod.ZodEnum<["unverified", "basic_verified", "premium_verified"]>;
    verification_fee_paid: zod.ZodBoolean;
    verification_badge: zod.ZodEnum<["none", "basic_verified", "premium_verified"]>;
    requested_tier: zod.ZodOptional<zod.ZodEnum<["basic_verified", "premium_verified"]>>;
    subscription_plan: zod.ZodEnum<["starter", "growth", "pro"]>;
    free_boosts: zod.ZodNumber;
    is_founding_seller: zod.ZodBoolean;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}>;
export declare const ListUsersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
    verification_status: zod.ZodEnum<["unverified", "basic_verified", "premium_verified"]>;
    verification_fee_paid: zod.ZodBoolean;
    verification_badge: zod.ZodEnum<["none", "basic_verified", "premium_verified"]>;
    requested_tier: zod.ZodOptional<zod.ZodEnum<["basic_verified", "premium_verified"]>>;
    subscription_plan: zod.ZodEnum<["starter", "growth", "pro"]>;
    free_boosts: zod.ZodNumber;
    is_founding_seller: zod.ZodBoolean;
    created_at: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}, {
    id: string;
    created_at: Date;
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
    verification_status: "basic_verified" | "premium_verified" | "unverified";
    verification_fee_paid: boolean;
    verification_badge: "basic_verified" | "premium_verified" | "none";
    subscription_plan: "starter" | "growth" | "pro";
    free_boosts: number;
    is_founding_seller: boolean;
    requested_tier?: "basic_verified" | "premium_verified" | undefined;
}>, "many">;
/**
 * Register a new user on GemWorld
 * @summary Create a new user
 */
export declare const CreateUserBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["buyer", "seller", "admin"]>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
}, {
    name: string;
    email: string;
    role: "buyer" | "seller" | "admin";
}>;
//# sourceMappingURL=api.d.ts.map