/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminVerificationAction,
  BoostListingRequest,
  BoostPackPurchaseResult,
  BoostResult,
  BuyBoostPackRequest,
  CreateGemstoneRequest,
  CreatePaymentRequest,
  CreateTransactionRequest,
  CreateUserRequest,
  CreditSummary,
  ErrorResponse,
  Gemstone,
  GetBuyerCreditSummaryParams,
  HealthStatus,
  LaunchConfig,
  Payment,
  SetLaunchPeriodRequest,
  Transaction,
  UpdateSubscriptionRequest,
  User,
  VerificationRequestBody,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Deducts one boost from the seller's available boosts and features the listing for 7 days
 * @summary Apply a boost to a gemstone listing
 */
export const getBoostListingUrl = (id: string) => {
  return `/api/inventory/${id}/boost`;
};

export const boostListing = async (
  id: string,
  boostListingRequest: BoostListingRequest,
  options?: RequestInit,
): Promise<BoostResult> => {
  return customFetch<BoostResult>(getBoostListingUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(boostListingRequest),
  });
};

export const getBoostListingMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boostListing>>,
    TError,
    { id: string; data: BodyType<BoostListingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof boostListing>>,
  TError,
  { id: string; data: BodyType<BoostListingRequest> },
  TContext
> => {
  const mutationKey = ["boostListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof boostListing>>,
    { id: string; data: BodyType<BoostListingRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return boostListing(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BoostListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof boostListing>>
>;
export type BoostListingMutationBody = BodyType<BoostListingRequest>;
export type BoostListingMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Apply a boost to a gemstone listing
 */
export const useBoostListing = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof boostListing>>,
    TError,
    { id: string; data: BodyType<BoostListingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof boostListing>>,
  TError,
  { id: string; data: BodyType<BoostListingRequest> },
  TContext
> => {
  return useMutation(getBoostListingMutationOptions(options));
};

/**
 * Adds boosts to the seller's available boost balance
 * @summary Purchase a boost pack
 */
export const getBuyBoostPackUrl = (id: string) => {
  return `/api/users/${id}/boost-packs`;
};

export const buyBoostPack = async (
  id: string,
  buyBoostPackRequest: BuyBoostPackRequest,
  options?: RequestInit,
): Promise<BoostPackPurchaseResult> => {
  return customFetch<BoostPackPurchaseResult>(getBuyBoostPackUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(buyBoostPackRequest),
  });
};

export const getBuyBoostPackMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof buyBoostPack>>,
    TError,
    { id: string; data: BodyType<BuyBoostPackRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof buyBoostPack>>,
  TError,
  { id: string; data: BodyType<BuyBoostPackRequest> },
  TContext
> => {
  const mutationKey = ["buyBoostPack"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof buyBoostPack>>,
    { id: string; data: BodyType<BuyBoostPackRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return buyBoostPack(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BuyBoostPackMutationResult = NonNullable<
  Awaited<ReturnType<typeof buyBoostPack>>
>;
export type BuyBoostPackMutationBody = BodyType<BuyBoostPackRequest>;
export type BuyBoostPackMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Purchase a boost pack
 */
export const useBuyBoostPack = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof buyBoostPack>>,
    TError,
    { id: string; data: BodyType<BuyBoostPackRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof buyBoostPack>>,
  TError,
  { id: string; data: BodyType<BuyBoostPackRequest> },
  TContext
> => {
  return useMutation(getBuyBoostPackMutationOptions(options));
};

/**
 * @summary Get current launch period status and pricing
 */
export const getGetLaunchConfigUrl = () => {
  return `/api/admin/launch`;
};

export const getLaunchConfig = async (
  options?: RequestInit,
): Promise<LaunchConfig> => {
  return customFetch<LaunchConfig>(getGetLaunchConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLaunchConfigQueryKey = () => {
  return [`/api/admin/launch`] as const;
};

export const getGetLaunchConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getLaunchConfig>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLaunchConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLaunchConfigQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLaunchConfig>>> = ({
    signal,
  }) => getLaunchConfig({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLaunchConfig>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLaunchConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLaunchConfig>>
>;
export type GetLaunchConfigQueryError = ErrorType<unknown>;

/**
 * @summary Get current launch period status and pricing
 */

export function useGetLaunchConfig<
  TData = Awaited<ReturnType<typeof getLaunchConfig>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLaunchConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLaunchConfigQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Enable or disable the launch period
 */
export const getSetLaunchPeriodUrl = () => {
  return `/api/admin/launch`;
};

export const setLaunchPeriod = async (
  setLaunchPeriodRequest: SetLaunchPeriodRequest,
  options?: RequestInit,
): Promise<LaunchConfig> => {
  return customFetch<LaunchConfig>(getSetLaunchPeriodUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(setLaunchPeriodRequest),
  });
};

export const getSetLaunchPeriodMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setLaunchPeriod>>,
    TError,
    { data: BodyType<SetLaunchPeriodRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setLaunchPeriod>>,
  TError,
  { data: BodyType<SetLaunchPeriodRequest> },
  TContext
> => {
  const mutationKey = ["setLaunchPeriod"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setLaunchPeriod>>,
    { data: BodyType<SetLaunchPeriodRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return setLaunchPeriod(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetLaunchPeriodMutationResult = NonNullable<
  Awaited<ReturnType<typeof setLaunchPeriod>>
>;
export type SetLaunchPeriodMutationBody = BodyType<SetLaunchPeriodRequest>;
export type SetLaunchPeriodMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Enable or disable the launch period
 */
export const useSetLaunchPeriod = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setLaunchPeriod>>,
    TError,
    { data: BodyType<SetLaunchPeriodRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof setLaunchPeriod>>,
  TError,
  { data: BodyType<SetLaunchPeriodRequest> },
  TContext
> => {
  return useMutation(getSetLaunchPeriodMutationOptions(options));
};

/**
 * Buyer creates a new transaction for a gemstone
 * @summary Create a transaction request
 */
export const getCreateTransactionUrl = () => {
  return `/api/transactions`;
};

export const createTransaction = async (
  createTransactionRequest: CreateTransactionRequest,
  options?: RequestInit,
): Promise<Transaction> => {
  return customFetch<Transaction>(getCreateTransactionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTransactionRequest),
  });
};

export const getCreateTransactionMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTransaction>>,
    TError,
    { data: BodyType<CreateTransactionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTransaction>>,
  TError,
  { data: BodyType<CreateTransactionRequest> },
  TContext
> => {
  const mutationKey = ["createTransaction"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTransaction>>,
    { data: BodyType<CreateTransactionRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createTransaction(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTransactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTransaction>>
>;
export type CreateTransactionMutationBody = BodyType<CreateTransactionRequest>;
export type CreateTransactionMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a transaction request
 */
export const useCreateTransaction = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTransaction>>,
    TError,
    { data: BodyType<CreateTransactionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTransaction>>,
  TError,
  { data: BodyType<CreateTransactionRequest> },
  TContext
> => {
  return useMutation(getCreateTransactionMutationOptions(options));
};

/**
 * Record a payment against a transaction
 * @summary Record a payment
 */
export const getCreatePaymentUrl = () => {
  return `/api/payments`;
};

export const createPayment = async (
  createPaymentRequest: CreatePaymentRequest,
  options?: RequestInit,
): Promise<Payment> => {
  return customFetch<Payment>(getCreatePaymentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPaymentRequest),
  });
};

export const getCreatePaymentMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentRequest> },
  TContext
> => {
  const mutationKey = ["createPayment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPayment>>,
    { data: BodyType<CreatePaymentRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createPayment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPayment>>
>;
export type CreatePaymentMutationBody = BodyType<CreatePaymentRequest>;
export type CreatePaymentMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Record a payment
 */
export const useCreatePayment = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentRequest> },
  TContext
> => {
  return useMutation(getCreatePaymentMutationOptions(options));
};

/**
 * Returns credit score, total outstanding and overdue amounts for a buyer. Only accessible to PRO plan sellers.
 * @summary Get buyer credit summary (PRO sellers only)
 */
export const getGetBuyerCreditSummaryUrl = (
  id: string,
  params: GetBuyerCreditSummaryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/buyers/${id}/credit-summary?${stringifiedParams}`
    : `/api/buyers/${id}/credit-summary`;
};

export const getBuyerCreditSummary = async (
  id: string,
  params: GetBuyerCreditSummaryParams,
  options?: RequestInit,
): Promise<CreditSummary> => {
  return customFetch<CreditSummary>(getGetBuyerCreditSummaryUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getGetBuyerCreditSummaryQueryKey = (
  id: string,
  params?: GetBuyerCreditSummaryParams,
) => {
  return [
    `/api/buyers/${id}/credit-summary`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetBuyerCreditSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getBuyerCreditSummary>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  params: GetBuyerCreditSummaryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBuyerCreditSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBuyerCreditSummaryQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBuyerCreditSummary>>
  > = ({ signal }) =>
    getBuyerCreditSummary(id, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBuyerCreditSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBuyerCreditSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBuyerCreditSummary>>
>;
export type GetBuyerCreditSummaryQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get buyer credit summary (PRO sellers only)
 */

export function useGetBuyerCreditSummary<
  TData = Awaited<ReturnType<typeof getBuyerCreditSummary>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  params: GetBuyerCreditSummaryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBuyerCreditSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBuyerCreditSummaryQueryOptions(
    id,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update seller subscription plan
 */
export const getUpdateSubscriptionPlanUrl = (id: string) => {
  return `/api/users/${id}/subscription`;
};

export const updateSubscriptionPlan = async (
  id: string,
  updateSubscriptionRequest: UpdateSubscriptionRequest,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getUpdateSubscriptionPlanUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateSubscriptionRequest),
  });
};

export const getUpdateSubscriptionPlanMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSubscriptionPlan>>,
    TError,
    { id: string; data: BodyType<UpdateSubscriptionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSubscriptionPlan>>,
  TError,
  { id: string; data: BodyType<UpdateSubscriptionRequest> },
  TContext
> => {
  const mutationKey = ["updateSubscriptionPlan"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSubscriptionPlan>>,
    { id: string; data: BodyType<UpdateSubscriptionRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateSubscriptionPlan(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSubscriptionPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSubscriptionPlan>>
>;
export type UpdateSubscriptionPlanMutationBody =
  BodyType<UpdateSubscriptionRequest>;
export type UpdateSubscriptionPlanMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Update seller subscription plan
 */
export const useUpdateSubscriptionPlan = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSubscriptionPlan>>,
    TError,
    { id: string; data: BodyType<UpdateSubscriptionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateSubscriptionPlan>>,
  TError,
  { id: string; data: BodyType<UpdateSubscriptionRequest> },
  TContext
> => {
  return useMutation(getUpdateSubscriptionPlanMutationOptions(options));
};

/**
 * User pays the verification fee and requests a tier upgrade
 * @summary Submit verification fee payment
 */
export const getSubmitVerificationRequestUrl = (id: string) => {
  return `/api/users/${id}/verification-request`;
};

export const submitVerificationRequest = async (
  id: string,
  verificationRequestBody: VerificationRequestBody,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getSubmitVerificationRequestUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(verificationRequestBody),
  });
};

export const getSubmitVerificationRequestMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitVerificationRequest>>,
    TError,
    { id: string; data: BodyType<VerificationRequestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitVerificationRequest>>,
  TError,
  { id: string; data: BodyType<VerificationRequestBody> },
  TContext
> => {
  const mutationKey = ["submitVerificationRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitVerificationRequest>>,
    { id: string; data: BodyType<VerificationRequestBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return submitVerificationRequest(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitVerificationRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitVerificationRequest>>
>;
export type SubmitVerificationRequestMutationBody =
  BodyType<VerificationRequestBody>;
export type SubmitVerificationRequestMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Submit verification fee payment
 */
export const useSubmitVerificationRequest = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitVerificationRequest>>,
    TError,
    { id: string; data: BodyType<VerificationRequestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitVerificationRequest>>,
  TError,
  { id: string; data: BodyType<VerificationRequestBody> },
  TContext
> => {
  return useMutation(getSubmitVerificationRequestMutationOptions(options));
};

/**
 * @summary Admin approves or rejects a verification request
 */
export const getAdminVerifyUserUrl = (id: string) => {
  return `/api/users/${id}/verification`;
};

export const adminVerifyUser = async (
  id: string,
  adminVerificationAction: AdminVerificationAction,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getAdminVerifyUserUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminVerificationAction),
  });
};

export const getAdminVerifyUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminVerifyUser>>,
    TError,
    { id: string; data: BodyType<AdminVerificationAction> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminVerifyUser>>,
  TError,
  { id: string; data: BodyType<AdminVerificationAction> },
  TContext
> => {
  const mutationKey = ["adminVerifyUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminVerifyUser>>,
    { id: string; data: BodyType<AdminVerificationAction> }
  > = (props) => {
    const { id, data } = props ?? {};

    return adminVerifyUser(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminVerifyUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminVerifyUser>>
>;
export type AdminVerifyUserMutationBody = BodyType<AdminVerificationAction>;
export type AdminVerifyUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Admin approves or rejects a verification request
 */
export const useAdminVerifyUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminVerifyUser>>,
    TError,
    { id: string; data: BodyType<AdminVerificationAction> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminVerifyUser>>,
  TError,
  { id: string; data: BodyType<AdminVerificationAction> },
  TContext
> => {
  return useMutation(getAdminVerifyUserMutationOptions(options));
};

/**
 * Returns all gemstones listed on GemWorld
 * @summary List all gemstones
 */
export const getListInventoryUrl = () => {
  return `/api/inventory`;
};

export const listInventory = async (
  options?: RequestInit,
): Promise<Gemstone[]> => {
  return customFetch<Gemstone[]>(getListInventoryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListInventoryQueryKey = () => {
  return [`/api/inventory`] as const;
};

export const getListInventoryQueryOptions = <
  TData = Awaited<ReturnType<typeof listInventory>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listInventory>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListInventoryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listInventory>>> = ({
    signal,
  }) => listInventory({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listInventory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListInventoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof listInventory>>
>;
export type ListInventoryQueryError = ErrorType<unknown>;

/**
 * @summary List all gemstones
 */

export function useListInventory<
  TData = Awaited<ReturnType<typeof listInventory>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listInventory>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListInventoryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Seller adds a new gemstone to inventory
 * @summary Add a gemstone listing
 */
export const getAddGemstoneUrl = () => {
  return `/api/inventory`;
};

export const addGemstone = async (
  createGemstoneRequest: CreateGemstoneRequest,
  options?: RequestInit,
): Promise<Gemstone> => {
  return customFetch<Gemstone>(getAddGemstoneUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createGemstoneRequest),
  });
};

export const getAddGemstoneMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addGemstone>>,
    TError,
    { data: BodyType<CreateGemstoneRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addGemstone>>,
  TError,
  { data: BodyType<CreateGemstoneRequest> },
  TContext
> => {
  const mutationKey = ["addGemstone"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addGemstone>>,
    { data: BodyType<CreateGemstoneRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return addGemstone(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddGemstoneMutationResult = NonNullable<
  Awaited<ReturnType<typeof addGemstone>>
>;
export type AddGemstoneMutationBody = BodyType<CreateGemstoneRequest>;
export type AddGemstoneMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Add a gemstone listing
 */
export const useAddGemstone = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addGemstone>>,
    TError,
    { data: BodyType<CreateGemstoneRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addGemstone>>,
  TError,
  { data: BodyType<CreateGemstoneRequest> },
  TContext
> => {
  return useMutation(getAddGemstoneMutationOptions(options));
};

/**
 * Returns a list of all registered users
 * @summary List all users
 */
export const getListUsersUrl = () => {
  return `/api/users`;
};

export const listUsers = async (options?: RequestInit): Promise<User[]> => {
  return customFetch<User[]>(getListUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListUsersQueryKey = () => {
  return [`/api/users`] as const;
};

export const getListUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({
    signal,
  }) => listUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsers>>
>;
export type ListUsersQueryError = ErrorType<unknown>;

/**
 * @summary List all users
 */

export function useListUsers<
  TData = Awaited<ReturnType<typeof listUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Register a new user on GemWorld
 * @summary Create a new user
 */
export const getCreateUserUrl = () => {
  return `/api/users`;
};

export const createUser = async (
  createUserRequest: CreateUserRequest,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getCreateUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserRequest),
  });
};

export const getCreateUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    { data: BodyType<CreateUserRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  { data: BodyType<CreateUserRequest> },
  TContext
> => {
  const mutationKey = ["createUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUser>>,
    { data: BodyType<CreateUserRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>;
export type CreateUserMutationBody = BodyType<CreateUserRequest>;
export type CreateUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a new user
 */
export const useCreateUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    { data: BodyType<CreateUserRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  { data: BodyType<CreateUserRequest> },
  TContext
> => {
  return useMutation(getCreateUserMutationOptions(options));
};
