/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export interface BoostResult {
    gemstone_id: string;
    is_featured: boolean;
    boost_expiry_date: Date;
    boosts_remaining: number;
    boost_cost_usd: number;
    expires_in_days: number;
}
//# sourceMappingURL=boostResult.d.ts.map