/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type BoostPackType = (typeof BoostPackType)[keyof typeof BoostPackType];
export declare const BoostPackType: {
    readonly boosts_5: "boosts_5";
    readonly boosts_10: "boosts_10";
};
//# sourceMappingURL=boostPackType.d.ts.map