/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { BoostPackType } from "./boostPackType";
export interface BoostPackPurchaseResult {
    pack: BoostPackType;
    boosts_added: number;
    cost_usd: number;
    boosts_available: number;
    standard_price_per_boost: number;
    effective_price_per_boost: number;
}
//# sourceMappingURL=boostPackPurchaseResult.d.ts.map