/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { Currency } from "./currency";
export interface CreateGemstoneRequest {
    seller_id: string;
    /** @minLength 1 */
    stone_type: string;
    /** @minimum 0 */
    carat: number;
    /** @minLength 1 */
    origin: string;
    /** @minLength 1 */
    treatment: string;
    /** GIA colour grade (D–M). Required when stone_type is diamond. */
    color?: string;
    /** GIA clarity grade. Required when stone_type is diamond. */
    clarity?: string;
    /** @minimum 0 */
    price: number;
    currency: Currency;
    /** @minLength 1 */
    certificate_number: string;
    /** @minLength 1 */
    image_url: string;
}
//# sourceMappingURL=createGemstoneRequest.d.ts.map