/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";
export interface CreateUserRequest {
    /** @minLength 1 */
    name: string;
    email: string;
    role: UserRole;
}
//# sourceMappingURL=createUserRequest.d.ts.map