/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { Currency } from "./currency";
export interface CreateTransactionRequest {
    buyer_id: string;
    seller_id: string;
    inventory_id: string;
    /** @minimum 0 */
    total_amount: number;
    currency: Currency;
    /** @minimum 0 */
    advance_paid: number;
    /** @minimum 0 */
    credit_amount: number;
    due_date: Date;
}
//# sourceMappingURL=createTransactionRequest.d.ts.map