/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { Transaction } from "./transaction";
export interface CreditSummary {
    buyer_id: string;
    /**
     * Computed credit score (300–850). Higher is better.
     * @minimum 300
     * @maximum 850
     */
    credit_score: number;
    /** Human-readable rating derived from credit score */
    credit_rating: string;
    total_outstanding: number;
    overdue_amount: number;
    completed_transactions: number;
    overdue_transactions: number;
    transactions: Transaction[];
}
//# sourceMappingURL=creditSummary.d.ts.map