/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type Currency = (typeof Currency)[keyof typeof Currency];
export declare const Currency: {
    readonly USD: "USD";
    readonly INR: "INR";
    readonly AED: "AED";
};
//# sourceMappingURL=currency.d.ts.map