/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { Currency } from "./currency";
import type { GemstonePricingConfidence } from "./gemstonePricingConfidence";
export interface Gemstone {
    id: string;
    seller_id: string;
    stone_type: string;
    /** @minimum 0 */
    carat: number;
    origin: string;
    treatment: string;
    /** @minimum 0 */
    price: number;
    currency: Currency;
    /** @minimum 0 */
    base_price_usd: number;
    certificate_number: string;
    image_url: string;
    /** GIA colour grade (D–M). Required for diamonds. */
    color?: string | null;
    /** GIA clarity grade (IF, VVS1, VVS2, VS1, VS2, SI1, SI2, I1, I2, I3). Required for diamonds. */
    clarity?: string | null;
    /** Rapaport Benchmark Price (USD/carat). Diamonds only. */
    rap_price_per_carat?: number | null;
    /** Total Rapaport value = rap_price_per_carat × carat. Diamonds only. */
    total_rap_value?: number | null;
    is_featured: boolean;
    boost_expiry_date?: Date | null;
    /**
     * Estimated Trade Range — floor (USD). Diamonds: 60% of Rap. Others: rule-based.
     * @minimum 0
     */
    estimated_price_min: number;
    /**
     * Estimated Trade Range — ceiling (USD). Diamonds: 90% of Rap. Others: rule-based.
     * @minimum 0
     */
    estimated_price_max: number;
    /** Confidence level for the estimated price range */
    pricing_confidence: GemstonePricingConfidence;
    /** Disclaimer for the estimated price */
    pricing_disclaimer: string;
    created_at: Date;
}
//# sourceMappingURL=gemstone.d.ts.map