/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
/**
 * Confidence level for the estimated price range
 */
export type GemstonePricingConfidence = (typeof GemstonePricingConfidence)[keyof typeof GemstonePricingConfidence];
export declare const GemstonePricingConfidence: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
//# sourceMappingURL=gemstonePricingConfidence.d.ts.map