/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type GetBuyerCreditSummaryParams = {
    /**
     * The seller's user ID making this request
     */
    requester_id: string;
};
//# sourceMappingURL=getBuyerCreditSummaryParams.d.ts.map