/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { LaunchPricing } from "./launchPricing";
import type { LaunchVerificationFees } from "./launchVerificationFees";
export interface LaunchConfig {
    is_launch_period: boolean;
    verification_fees: LaunchVerificationFees;
    subscription_pricing: LaunchPricing;
    free_boosts_granted: number;
}
//# sourceMappingURL=launchConfig.d.ts.map