/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export interface SetLaunchPeriodRequest {
    is_launch_period: boolean;
}
//# sourceMappingURL=setLaunchPeriodRequest.d.ts.map