/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type SubscriptionPlan = (typeof SubscriptionPlan)[keyof typeof SubscriptionPlan];
export declare const SubscriptionPlan: {
    readonly starter: "starter";
    readonly growth: "growth";
    readonly pro: "pro";
};
//# sourceMappingURL=subscriptionPlan.d.ts.map