/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus];
export declare const TransactionStatus: {
    readonly pending: "pending";
    readonly completed: "completed";
    readonly overdue: "overdue";
};
//# sourceMappingURL=transactionStatus.d.ts.map