/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
export declare const UserRole: {
    readonly buyer: "buyer";
    readonly seller: "seller";
    readonly admin: "admin";
};
//# sourceMappingURL=userRole.d.ts.map