/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionPlan } from "./subscriptionPlan";
import type { UserRole } from "./userRole";
import type { VerifiableTier } from "./verifiableTier";
import type { VerificationBadge } from "./verificationBadge";
import type { VerificationStatus } from "./verificationStatus";
export interface User {
    id: string;
    name: string;
    email: string;
    role: UserRole;
    verification_status: VerificationStatus;
    verification_fee_paid: boolean;
    verification_badge: VerificationBadge;
    requested_tier?: VerifiableTier;
    subscription_plan: SubscriptionPlan;
    /** @minimum 0 */
    free_boosts: number;
    is_founding_seller: boolean;
    created_at: Date;
}
//# sourceMappingURL=user.d.ts.map