/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type VerifiableTier = (typeof VerifiableTier)[keyof typeof VerifiableTier];
export declare const VerifiableTier: {
    readonly basic_verified: "basic_verified";
    readonly premium_verified: "premium_verified";
};
//# sourceMappingURL=verifiableTier.d.ts.map