/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type VerificationBadge = (typeof VerificationBadge)[keyof typeof VerificationBadge];
export declare const VerificationBadge: {
    readonly none: "none";
    readonly basic_verified: "basic_verified";
    readonly premium_verified: "premium_verified";
};
//# sourceMappingURL=verificationBadge.d.ts.map