/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * GemWorld B2B Gemstone Marketplace API
 * OpenAPI spec version: 0.1.0
 */
export type VerificationStatus = (typeof VerificationStatus)[keyof typeof VerificationStatus];
export declare const VerificationStatus: {
    readonly unverified: "unverified";
    readonly basic_verified: "basic_verified";
    readonly premium_verified: "premium_verified";
};
//# sourceMappingURL=verificationStatus.d.ts.map